02/01/23 (16:45:51) | ERROR: Exception when sending signal 9 to pid 61390
02/01/23 (16:45:51) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
02/01/23 (16:45:52) | ERROR: Exception when sending signal 9 to pid 541
02/01/23 (16:45:52) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
02/01/23 (16:45:59) | ERROR: Exception when sending signal 9 to pid 61390
02/01/23 (16:45:59) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
